server:
  port: 80

#服务别名 注册zookeeper到注册中心服务名称
spring:
  application:
    name: cloud-consumer-order
  cloud:
    zookeeper:
      connect-string: 192.168.0.128:2181,192.168.0.129:2181,192.168.0.130:2181
