server:
  port: 3344
spring:
  application:
    name: cloud-config-center #注册eureka服务器的微服务名
  cloud:
    config:
      server:
        #http://config-3344.com:3344/master/config-dev.yml
        git:
          uri: https://github.com/zhelica/springcloud-config.git #github上面的仓库名字
          #搜索目录
          search-paths:
            - springcloud-config
      #读取分支
      label: master
  #rabbitmq相关配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      #设置eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

#暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"
