server:
  port: 80

#服务别名 注册zookeeper到注册中心服务名称
spring:
  application:
    name: cloud-consumer-order
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
