server:
  port: 80
eureka:
  client:
    #注册
    register-with-eureka: false
    service-url:
      #设置eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
#服务降级
feign:
  hystrix:
    enabled: true
